image:
- Ubuntu

version: ci.appveyor.0.{build}.ci.{build}

build_script:
  - echo "My emscripten build"
  - mkdir -p build
  - cd build
  - cmake -DCMAKE_TOOLCHAIN_FILE=../emsdk/upstream/emscripten/cmake/Modules/Platform/Emscripten.cmake -DCMAKE_BUILD_TYPE=Release ..
  - make

install:
  - git clone https://github.com/emscripten-core/emsdk.git
  - cd emsdk
  - ./emsdk install latest
  - ./emsdk activate latest  
  - source ./emsdk_env.sh
  - sudo apt-get install cmake -y
  - cd ..
  - git submodule init
  - git submodule update
  
test_script:
  - echo "Test for World.JS"
