name: CMake

on: [push]

env:
  BUILD_TYPE: Release
  EM_CACHE_FOLDER: 'emsdk-cache'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Checkout submodules
      uses: textbook/git-checkout-submodule-action@master
    
    - name: Add emsdk
      uses: mymindstorm/setup-emsdk@v7
      with:
        actions-cache-folder: ${{env.EM_CACHE_FOLDER}}
    
    - name: Test env
      run: emcc -v
        
    - name: Build
      run: >
          mkdir build;
          cd build;
          emcmake cmake ..;
          cmake --build . --config Release;
