name: CMake

on: [push]

env:
  BUILD_TYPE: Release
  EM_VERSION: 1.39.18
  EM_CACHE_FOLDER: 'emsdk-cache'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Checkout submodules
      uses: textbook/git-checkout-submodule-action@master
    
    - name: Add emsdk
      uses: mymindstorm/setup-emsdk@v7
      with:
        version: ${{env.EM_VERSION}}
        actions-cache-folder: ${{env.EM_CACHE_FOLDER}}
    
    - name: Test env
      run: emcc -v
        
    - name: Create Build Environment
      run: cmake -E make_directory ${{github.workspace}}/build

    - name: Build
      working-directory: ${{github.workspace}}/build
      shell: bash
      run: >
          emcmake cmake .
          make -j
